add GHOST logos
CityOfZion/neon-wallet pull request #2331
Opened 2021-11-22 03:16 UTC by vincentgeneste

**What problem does this PR solve?**

Fixing that: 

[PitchDeck-GM-November-2021.pdf](https://github.com/CityOfZion/neon-wallet/files/7578002/PitchDeck-GM-November-2021.pdf)

**How did you solve this problem?**

adding logos

2021-11-23 15:26 UTC, comountainclimber commented on app/assets/nep5/svg/index.js
>    NEO,
If you are not also exporting the asset here this code is noop... Have you verified that this PR works? If it does I am super confused as to how its working

2021-11-23 15:27 UTC, comountainclimber requested changes
See comment above

2021-11-23 16:44 UTC, vincentgeneste commented on app/assets/nep5/svg/index.js
>    NEO,
haerm, my bad it's a miss on the PR, will fix now.

2021-11-29 18:55 UTC, comountainclimber approved these changes

2021-11-29 18:55 UTC, merged