feature: remove infinite scroll on activity screen
CityOfZion/neon-wallet pull request #2503
Opened 2023-06-14 18:48 UTC by comountainclimber

**What current issue(s) from Trello/Github does this address?**
![Kapture 2023-06-14 at 12 29 55](https://github.com/CityOfZion/neon-wallet/assets/13072035/ab9746cf-bc3c-4353-a4f0-dcef85adb4cb)

**What problem does this PR solve?**

**How did you solve this problem?**

**How did you make sure your solution works?**

**Are there any special changes in the code that we should be aware of?**

**Is there anything else we should know?**

- [ ] Unit tests written?

2023-06-14 19:01 UTC, melanke requested changes

2023-06-14 19:01 UTC, melanke commented on app/containers/TransactionHistory/TransactionHistory.scss
> +  // max-height: calc(100vh - 120px) !important;
Usually it's a bad idea leave commented code because we never know if this code should be removed or the comment was only to test and commited by mistake. If you have the intention to uncomment, it's better to put a "TODO" comment above it.

2023-06-14 19:01 UTC, melanke commented on app/actions/transactionHistoryActions.js
> +      // console.log({ data })
same thing here

2023-06-14 19:02 UTC, comountainclimber commented on app/containers/TransactionHistory/TransactionHistory.scss
> +  // max-height: calc(100vh - 120px) !important;
Totally agree... This was meant to be removed 🙈

2023-06-19 16:36 UTC, melanke approved these changes

2023-06-20 15:35 UTC, merged