CU-86a129e36 - Login Screen Implementation
CityOfZion/neon-wallet pull request #2550
Opened 2023-10-26 21:07 UTC by yumiuehara

**What current issue(s) from Trello/Github does this address?**

**What problem does this PR solve?**

**How did you solve this problem?**

**How did you make sure your solution works?**

**Are there any special changes in the code that we should be aware of?**

**Is there anything else we should know?**

- [ ] Unit tests written?

2023-10-26 21:07 UTC, lllwvlvwlll commented
Task linked: [CU-86a129e36 Login Screen Implementation](https://app.clickup.com/t/86a129e36)

2023-10-26 21:07 UTC, lllwvlvwlll commented
Task linked: [CU-86a129e36 Login Screen Implementation](https://app.clickup.com/t/86a129e36)

2023-10-27 00:32 UTC, raulduartep commented on src/renderer/src/pages/Login/index.tsx
> +  const wallets = useSelectorRef(state => state.wallet.data)
```suggestion
import { selectWallets } from '@renderer/store/wallet/SelectorWallet'

  const wallets = useSelectorRef(selectWallets)
```

2023-10-27 00:33 UTC, raulduartep commented on src/renderer/src/pages/Login/index.tsx
> +  const accounts = useSelectorRef(state => state.account.data)
```suggestion
import { selectAccounts } from '@renderer/store/account/SelectorAccount'

  const accounts = useSelectorRef(selectAccounts)
```

2023-10-27 00:34 UTC, raulduartep commented on src/renderer/src/pages/Login/index.tsx
> +  const isFirstTimeRef = useSelectorRef(state => state.settings.isFirstTime)
Change the useSelectorRef to  useSelector

2023-10-27 00:39 UTC, raulduartep requested changes

2023-10-27 00:39 UTC, raulduartep commented on src/renderer/src/pages/Login/index.tsx
> +  const wallets = useSelectorRef(state => state.wallet.data)
```suggestion
  import { selectWallets } from '@renderer/store/wallet/SelectorWallet'
	
	  const wallets = useSelectorRef(selectWallets)
```

2023-10-27 00:39 UTC, raulduartep commented on src/renderer/src/pages/Login/index.tsx
> +  const accounts = useSelectorRef(state => state.account.data)
```suggestion
  import { selectAccounts } from '@renderer/store/account/SelectorAccount'
	
	  const accounts = useSelectorRef(selectAccounts)
```

2023-10-27 20:46 UTC, raulduartep commented on src/renderer/src/pages/Login/index.tsx
> +  const bsAggregator = useSelectorRef(state => state.blockchain.bsAggregator)
```suggestion
  const bsAggregator = useSelectorRef(selectBsAggregator)
```

2023-10-30 14:27 UTC, raulduartep requested changes

2023-10-30 14:27 UTC, raulduartep commented on src/renderer/src/pages/Login/index.tsx
> +  const bsAggregator = useSelectorRef(state => state.blockchain.bsAggregator)
```suggestion
  const bsAggregator = useSelectorRef(selectBsAggregator)
```

2023-10-30 14:45 UTC, raulduartep approved these changes

2023-10-30 14:51 UTC, merged