CU-8678g209y - nwd: encrypt, decrypt and decryptFromArray WC's methods
CityOfZion/neon-wallet pull request #2552
Opened 2023-10-27 18:33 UTC by endkeyCoder

**What current issue(s) from Trello/Github does this address?**

**What problem does this PR solve?**

**How did you solve this problem?**

**How did you make sure your solution works?**

**Are there any special changes in the code that we should be aware of?**

**Is there anything else we should know?**

- [ ] Unit tests written?

2023-10-27 18:33 UTC, lllwvlvwlll commented
Task linked: [CU-8678g209y nwd: encrypt, decrypt and decryptFromArray WC's methods ](https://app.clickup.com/t/8678g209y)

2023-10-30 11:31 UTC, melanke requested changes

2023-10-30 11:31 UTC, melanke commented on app/components/DappRequest/MessageSuccess.jsx
> +const MessageSuccess = ({ isVerify, text }: Props) => {
Remove the `isVerify` parameter and change who is using this component to pass the whole text as parameter

2023-10-30 18:57 UTC, melanke approved these changes

2023-10-30 18:57 UTC, merged