CU-86a16b5d5 - NEON3 - Wallet List + Account List
CityOfZion/neon-wallet pull request #2553
Opened 2023-10-27 18:39 UTC by raulduartep

2023-10-27 18:39 UTC, lllwvlvwlll commented
Task linked: [CU-86a16b5d5 NEON3 - Wallet List + Account List](https://app.clickup.com/t/86a16b5d5)

2023-10-27 18:39 UTC, lllwvlvwlll commented
Task linked: [CU-86a16b5d5 NEON3 - Wallet List + Account List](https://app.clickup.com/t/86a16b5d5)

2023-10-30 11:38 UTC, melanke requested changes

2023-10-30 11:38 UTC, melanke commented on src/renderer/src/components/AccountCard.tsx
> +          {/* TODO: REPLACE THE MOCKED DATA WHEN THERE IS A SOLUTION FOR BALANCE VARIATION */}
Is there a task for this? Put the link or task code on this TODO coomment, please.

2023-10-30 11:38 UTC, melanke commented on src/renderer/src/components/WalletCard.tsx
> +          {/* TODO: REPLACE THE MOCKED DATA WHEN THERE IS A SOLUTION FOR BALANCE VARIATION */}
do the same think on all "TODO" comments of the application. This can become a nightmare to maintain.

2023-10-30 16:49 UTC, merged