CU-86a1jhbyg - NEON3 - Implement Dapp Connection Process
CityOfZion/neon-wallet pull request #2589
Opened 2023-12-08 17:20 UTC by raulduartep

2023-12-08 17:20 UTC, lllwvlvwlll commented
Task linked: [CU-86a1jhbyg NEON3 - Implement Dapp Connection Process](https://app.clickup.com/t/86a1jhbyg)

2023-12-11 13:50 UTC, melanke requested changes

2023-12-11 13:50 UTC, melanke commented on src/renderer/src/libs/walletConnectSDK.ts
> +    // TODO: Implement this method when ledger is supported
every TODO comment needs an issue code, otherwise it will be forgotten

2023-12-11 13:50 UTC, melanke commented on src/renderer/src/libs/walletConnectSDK.ts
> +    // TODO: Implement this method when ledger is supported
If you think this is not a real problem, ask Mirella and Lucas, but warning: they might scream at you LOL JK

2023-12-11 19:57 UTC, merged