CU-86a1vgfad - NWD2: Improve the experience when the user doesn't clo…
CityOfZion/neon-wallet pull request #2610
Opened 2024-01-24 02:37 UTC by raulduartep

…se the modal after accepting a WC request

**What current issue(s) from Trello/Github does this address?**

**What problem does this PR solve?**

**How did you solve this problem?**

**How did you make sure your solution works?**

**Are there any special changes in the code that we should be aware of?**

**Is there anything else we should know?**

- [ ] Unit tests written?

2024-01-24 02:37 UTC, lllwvlvwlll commented
Task linked: [CU-86a1vgfad NWD2: Improve the experience when the user doesn't close the modal after accepting a WC request](https://app.clickup.com/t/86a1vgfad)

2024-02-15 14:20 UTC, melanke requested changes

2024-02-15 14:20 UTC, melanke commented on app/containers/App/App.jsx
> +        })
leave a comment explaining this solution, please

2024-02-19 16:25 UTC, melanke approved these changes

2024-02-19 16:25 UTC, merged