CU-86dt26t4w - NEON3 - Settings Screen - MIGRATE from NEON2
CityOfZion/neon-wallet pull request #2690
Opened 2024-04-01 15:38 UTC by raulduartep

**What current issue(s) from Trello/Github does this address?**

**What problem does this PR solve?**

**How did you solve this problem?**

**How did you make sure your solution works?**

**Are there any special changes in the code that we should be aware of?**

**Is there anything else we should know?**

- [ ] Unit tests written?

2024-04-01 15:38 UTC, melanke commented
Task linked: [CU-86dt26t4w NEON3 - Settings Screen - MIGRATE from NEON2](https://app.clickup.com/t/86dt26t4w)

2024-04-02 17:54 UTC, yumiuehara requested changes

2024-04-02 17:54 UTC, yumiuehara commented on src/renderer/src/hooks/useBackupOrMigrate.ts
> +      ToastHelper.info({ message: 'Neon 3 backup file detected' })
the message string should be in one of the lang files

2024-04-02 17:54 UTC, yumiuehara commented on src/renderer/src/hooks/useBackupOrMigrate.ts
> +      ToastHelper.info({ message: 'Neon 2 migrate file detected' })
same here

2024-04-02 17:54 UTC, yumiuehara commented on src/renderer/src/locales/en/modals.json
> +      "passwordError": "Password not recognise!",
recognised

2024-04-02 17:54 UTC, yumiuehara commented on src/renderer/src/routes/pages/Settings/SettingsRecoverWallet/index.tsx
> +          {hasError && <AlertErrorBanner message="File not recognized" className="mt-4" />}
the message string should be in one of the lang files

2024-04-02 17:54 UTC, yumiuehara commented on src/renderer/src/routes/pages/Settings/SettingsEncryptKey/index.tsx
> +        <div className="max-w-[360px] w-full flex flex-grow flex-col">
maybe this should be rem instead of px?

2024-04-02 17:54 UTC, yumiuehara commented on src/renderer/src/@types/hooks.ts
> +  isActed: boolean
i don't think i understand this variable name. does it mean the it has already acted, so something like `hasActed`?

2024-04-03 17:07 UTC, merged